//
//  FortuneModel.swift
//  WeatherApp
//
//  Created by Oliwia Procyk on 08/05/2023.
//

import Foundation

struct FortuneModel {
    let fortunes = ["A great fortune awaits you.",
                    "Opportunities will knock on your door.",
                    "Good luck will follow you everywhere.",
                    "Financial success is in your future.",
                    "Love and happiness will find you.",
                    "You will achieve great things.",
                    "Your dreams will come true.",
                    "A prosperous journey lies ahead.",
                    "Fortune favors the brave.",
                    "Unexpected blessings will come your way.",
                    "Your talents will be recognized.",
                    "A windfall of abundance is coming your way.",
                    "You will be showered with good fortune.",
                    "Your hard work will pay off.",
                    "Luck is on your side.",
                    "Success will come easily to you.",
                    "You are destined for greatness.",
                    "Your financial situation will improve.",
                    "Exciting adventures await you.",
                    "The universe conspires in your favor.",
                    "New doors of opportunity will open for you.",
                    "Your positive attitude attracts prosperity.",
                    "You possess the power to manifest your dreams.",
                    "Abundance flows effortlessly into your life.",
                    "You are surrounded by supportive and loving relationships.",
                    "Success and recognition are on their way to you.",
                    "Your creativity knows no bounds.",
                    "You are blessed with abundant talents and skills.",
                    "Miracles happen in your presence.",
                    "The path to success is clear and accessible to you.",
                    "You are a magnet for wealth and success.",
                    "Your intuition guides you towards prosperous ventures.",
                    "Your determination leads to triumph.",
                    "You attract lucrative opportunities effortlessly.",
                    "Your financial resources multiply exponentially.",
                    "Love and prosperity flow harmoniously into your life.",
                    "Your efforts are rewarded generously.",
                    "You have the ability to turn challenges into opportunities.",
                    "You possess an unstoppable drive towards success.",
                    "Your positive energy attracts abundant blessings.",
                    "Your actions lead to abundant prosperity.",
                    "You are blessed with boundless creativity.",
                    "The universe supports your every endeavor.",
                    "Your dreams are within reach.",
                    "You radiate confidence and attract success.",
                    "Financial abundance is your birthright.",
                    "You are a magnet for wealth and abundance.",
                    "Your ideas are met with enthusiasm and support.",
                    "You are deserving of all the good that comes your way.",
                    "Your path is illuminated with opportunities.",
                    "You are surrounded by positive and uplifting people.",
                    "You are a beacon of success and inspiration.",
                    "Financial freedom is within your grasp.",
                    "Your hard work and dedication bring fruitful rewards.",
                    "You have a natural ability to attract prosperity.",
                    "You are capable of achieving extraordinary things.",
                    "Your positive mindset attracts positive outcomes.",
                    "Success follows you wherever you go.",
                    "You are aligned with the abundance of the universe.",
                    "Your wealth and success are increasing exponentially.",
                    "You are guided towards opportunities that align with your purpose.",
                    "You are blessed with infinite possibilities.",
                    "You attract joy and happiness into your life.",
                    "Your optimism paves the way for a prosperous future.",
                    "You have a magnetic presence that attracts success.",
                    "Abundance and prosperity are drawn to you.",
                    "Your actions align with your highest good.",
                    "You are surrounded by infinite opportunities for success."]
}
